name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      #      - name: Install dependencies
      #        if: steps.composer-cache.outputs.cache-hit != 'true'
      #        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Install dependencies
        uses: php-actions/composer@v5
        if: steps.composer-cache.outputs.cache-hit != 'true'
        with:
          php_version: 7.4
          version: 1
          args: --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: vendor/bin/phpunit

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./tests/reports/coverage-clover.xml
          flags: unittests
          fail_ci_if_error: true # optional (default = false)
